<?php

/**
 * @file
 * Ding Header Opening Hours module functionality.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function ding_header_opening_hours_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_block_info().
 */
function ding_header_opening_hours_block_info() {
  return array(
    'ding_header_opened_today' => array(
      'info' => t("Today's opening hours for main library"),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'ding_header_opened_today_all' => array(
      'info' => t("Today's opening hours for all libraries"),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function ding_header_opening_hours_block_view($delta = '') {
  $block = array();

  if ($delta == 'ding_header_opened_today') {
    $block['subject'] = '';
    $block['content'] = theme('ding_header_opened_today_view');

  }

  if ($delta == 'ding_header_opened_today_all') {
    $block['subject'] = t('Opened today');
    $block['content'] = theme('ding_header_opened_today_view_all');
  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function ding_header_opening_hours_theme($existing, $type, $theme, $path) {
  return array(
    'ding_header_opened_today_view' => array(
      'path' => $path . '/templates',
      'template' => 'ding_header_opened_today_view',
      'variables' => array('libraries' => NULL),
    ),
    'ding_header_opened_today_view_all' => array(
      'path' => $path . '/templates',
      'template' => 'ding_header_opened_today_view_all',
      'variables' => array('libraries' => NULL),
    ),
  );
}

/**
 * Preprocess variables for ding_header_opened_today_view.
 */
function template_preprocess_ding_header_opened_today_view(&$vars) {
  $libraries = array();
  $today = date('Y-m-d');

  // Load all libraries form list, because there are less libraries than dates
  // and because of how opening_hours_instance_load_multiple works.
  $sql = 'SELECT nq.qid, nq.show_in_tab, nq.show_in_links, nq.show_in_ui, nq.i18n ' .
    'FROM {nodequeue_queue} nq ' .
    'INNER JOIN {nodequeue_types} nt ON nt.qid = nq.qid ' .
    "WHERE nt.type = :type";
  $result = db_query($sql, array(':type' => 'ding_library'));
  $qids = array();
  foreach ($result as $qid) {
    $qids[$qid->qid] = $qid;
  }
  $queue_id = array_keys($qids);

  $nodes = nodequeue_load_nodes($queue_id[0], FALSE, 0, 1);

  if (!empty($nodes)) {
    foreach ($nodes as $library) {
      $libraries[$library->nid]['title'] = $library->title;
    }

    // Get all dates for today.
    if (!empty($libraries) > 0) {
      $opening_hours = opening_hours_instance_load_multiple(array_keys($libraries), $today, $today);
      $i = 0;
      foreach ($opening_hours as $hour) {
        if ($i < 2) {
          $libraries[$hour->nid]['opening_hours'][$i]['start_time'] = $hour->start_time;
          $libraries[$hour->nid]['opening_hours'][$i]['end_time'] = $hour->end_time;
          $libraries[$hour->nid]['opening_hours'][$i]['notice'] = $hour->notice;
          $i++;
        }
      }
    }
  }

  $vars['libraries'] = $libraries;
}

/**
 * Preprocess variables for ding_header_opened_today_view_all.
 */
function template_preprocess_ding_header_opened_today_view_all(&$vars) {
  $libraries = array();
  $today = date('Y-m-d');

  // Load all libraries form list, because there are less libraries than dates
  // and because of how opening_hours_instance_load_multiple works.
  $sql = 'SELECT nq.qid, nq.show_in_tab, nq.show_in_links, nq.show_in_ui, nq.i18n ' .
    'FROM {nodequeue_queue} nq ' .
    'INNER JOIN {nodequeue_types} nt ON nt.qid = nq.qid ' .
    "WHERE nt.type = :type";
  $result = db_query($sql, array(':type' => 'ding_library'));
  $qids = array();
  foreach ($result as $qid) {
    $qids[$qid->qid] = $qid;
  }
  $queue_id = array_keys($qids);

  $nodes = nodequeue_load_nodes($queue_id[0], FALSE, 0, 50);

  if (!empty($nodes)) {
    foreach ($nodes as $library) {
      $libraries[$library->nid]['title'] = l(
        $library->title,
        'node/' . $library->nid
      );
    }

    // Get all dates for today.
    if (!empty($libraries) > 0) {
      $opening_hours = opening_hours_instance_load_multiple(array_keys($libraries), $today, $today);
      $i = 0;
      foreach ($opening_hours as $hour) {
        $libraries[$hour->nid]['opening_hours'][$i]['start_time'] = $hour->start_time;
        $libraries[$hour->nid]['opening_hours'][$i]['end_time'] = $hour->end_time;
        $libraries[$hour->nid]['opening_hours'][$i]['notice'] = $hour->notice;
        $i++;
      }
    }
  }

  $vars['libraries'] = $libraries;
}
